export const REQUEST_FILMS = 'REQUEST_FILMS';
export const RECEIVE_FILMS = 'RECEIVE_FILMS';
export const TOGGLE_SORTING = 'TOGGLE_SORTING';
export const TOGGLE_SEARCH_BY = 'TOGGLE_SEARCH_BY';
export const REQUEST_FILM_BY_ID = 'REQUEST_FILM_BY_ID';
export const RECEIVE_FILM_BY_ID = 'RECEIVE_FILM';
export const GET_FILM_FROM_STATE = 'GET_FILM_FROM_STATE';
export const FILM_NOT_FOUND = 'FILM_NOT_FOUND';
